services:
  app:
    build:
      context: .
      dockerfile: ./.docker/go/Dockerfile
    container_name: huma-sample-app-dev
    volumes:
      - .:/app
    ports:
      - 8888:8888
    environment:
      - APP_ENV=development
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: huma-sample-nginx-dev
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    container_name: huma-sample-mysql-dev
    build:
      context: .
      dockerfile: ./.docker/mysql/Dockerfile
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - app-data-dev:/var/lib/mysql
      - ./auth/migrations:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - app-network

  # 開発用のAdminer（データベース管理ツール）
  adminer:
    image: adminer
    container_name: huma-sample-adminer-dev
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  app-data-dev:

networks:
  app-network:
    driver: bridge
